---

- name: download mms-backup
  local_action: >
    get_url
      url="{{mms_backup_download_url}}"
      dest="{{mms_backup_download_dir}}/{{mms_backup_package}}"
  tags: download

- name: unpacks mms-backup
  local_action: >
    unarchive
      src="{{mms_backup_download_dir}}/{{mms_backup_package}}"
      dest="{{mms_backup_download_dir}}/"
  tags: unpack

- name: ensures {{mms_backup_dir}}/{{mms_backup_install_dir}} exists
  file:
    path="{{mms_backup_dir}}/{{mms_backup_install_dir}}"
    state=directory
  tags: unpack

- name: ensures mms-backup is installed at {{mms_backup_dir}}/{{mms_backup_install_dir}}
  action: >
    synchronize
      src="{{mms_backup_download_dir}}/{{mms_backup_name_package}}/{{item}}"
      dest="{{mms_backup_dir}}/{{mms_backup_install_dir}}"
      archive=yes
      recursive=yes
  tags: unpack
  with_items:
    - mongodb-mms-backup-agent
    - local.config

- name: add hosts in /etc/hosts
  lineinfile: 
     dest=/etc/hosts 
     regexp='{{item.key}}$' 
     line='{{item.value}} {{item.key}}' 
     owner=root group=root mode=0644
  with_dict: mms_backup_hosts
  sudo: yes  

- name: change local.config
  template:
    src="local.config"
    dest="{{mms_backup_dir}}/{{mms_backup_install_dir}}/local.config"
    mode=0644
  tags: config
  notify: 
    - start mms-backup